import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Header from "@/components/header";
import { isUserAuthenticated } from "@/libs/firebase/firebase-admin";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isAuthenticated = isUserAuthenticated();

  return (
    <html lang="en">
      <body className={inter.className}>
        <Header isAuthenticatedPromise={isAuthenticated} />
        {children}
      </body>
    </html>
  );
}
